// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkilWMDjVov1B6QWoZzIOTDtvFKxIDO4Y',
    appId: '1:85080368333:web:f1a2f608cb07375810b584',
    messagingSenderId: '85080368333',
    projectId: 'agriconnect-0733',
    authDomain: 'agriconnect-0733.firebaseapp.com',
    databaseURL: 'https://agriconnect-0733-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agriconnect-0733.firebasestorage.app',
    measurementId: 'G-08FT0630VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYUVsn-zb_PvGzio-IKZfHqUDfIM1b--o',
    appId: '1:85080368333:android:ff0c4e9b047b4f5410b584',
    messagingSenderId: '85080368333',
    projectId: 'agriconnect-0733',
    databaseURL: 'https://agriconnect-0733-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agriconnect-0733.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuaPGEf8CpU3AsMRRdu9CqE6LjMcEKqwc',
    appId: '1:85080368333:ios:0ab05f00a765f56210b584',
    messagingSenderId: '85080368333',
    projectId: 'agriconnect-0733',
    databaseURL: 'https://agriconnect-0733-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agriconnect-0733.firebasestorage.app',
    iosBundleId: 'com.example.agriconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuaPGEf8CpU3AsMRRdu9CqE6LjMcEKqwc',
    appId: '1:85080368333:ios:0ab05f00a765f56210b584',
    messagingSenderId: '85080368333',
    projectId: 'agriconnect-0733',
    databaseURL: 'https://agriconnect-0733-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agriconnect-0733.firebasestorage.app',
    iosBundleId: 'com.example.agriconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkilWMDjVov1B6QWoZzIOTDtvFKxIDO4Y',
    appId: '1:85080368333:web:e56d837f72ef3e6310b584',
    messagingSenderId: '85080368333',
    projectId: 'agriconnect-0733',
    authDomain: 'agriconnect-0733.firebaseapp.com',
    databaseURL: 'https://agriconnect-0733-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agriconnect-0733.firebasestorage.app',
    measurementId: 'G-ME18JXH11C',
  );
}
